### ISSUE TITLE
It doesn't work !!!

### ISSUE THREAD

**Issue by vjagannath786** [timothelaborie/text_classification_scripts#1]
While testing the same code in kaggle it doesn't with the unsloth example.
It throws error indue out of range of prompt formatting function and if you exclude that collator doesn't work. 
Could have been better if a working example is given or link to the actual environment.

**Comment by timothelaborie** [comment]
can you include the full stack trace? It worked for me with these versions:
transformers==4.38.2
trl==0.7.10

**Comment by vjagannath786** [comment]
Hey,
Thanks for replying. Figured the issue instead of supplying empty string gave string with space and it worked.

def formatting_prompts_func(dataset_):
    # this is to fix an issue with a certain transformers version, you might not need this
    if isinstance(dataset_['text'], str):
        if model_name.lower().__contains__("qwen"):
            return [" "]*100
        elif model_name.lower().__contains__("llama"):
            return " "
        else:
            return " "
        
    texts = []
    for i in range(len(dataset_['text'])):
        t = dataset_['text'][i]
        label = positivelabel if dataset_['label'][i] == 1 else negativelabel
        text = prompt.format(t, label)


        texts.append(text)
    return texts

**Comment by timothelaborie** [comment]
Thanks, I modified the notebook.
