### ISSUE TITLE
Size Mismatch Issue

### ISSUE THREAD

**Issue by vjagannath786** [timothelaborie/text_classification_scripts#2]
The size of tensor a (128256) must match the size of tensor b (2) at non-singleton dimension 0

Getting this weird error while running the trainer.train() function, this worked perfectly fine until today. But suddenly getting this error. Nothing changed just running this notebook in colab gives the error at trainer.train function.

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/82c73471-ca41-4b8f-baeb-c805be27aa99">

**Comment by timothelaborie** [comment]
this is likely caused by some package like trl or transformers that changed something. I'll investigate in a few days (can't rn)
for now, maybe just remove the part that trims the classification head and the line that changes the label id

**Comment by timothelaborie** [comment]
fixed
